sudo: required

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

env:
    - MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=512m"
    
before_install:
    - "cd com.amitinside.featureflags"
  
install: mvn install -DskipTests=true -Dgpg.skip -e -X
