sudo: required

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_install:
      - "cd com.qivicon.featureflags"
      
install: mvn install -Dgpg.skip

after_success:
  - bash <(curl -s https://codecov.io/bash)
