sudo: required

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
      
-before_install:
    - "cd com.amitinside.featureflags.core"

install: mvn install -Dgpg.skip

after_success:
  - bash <(curl -s https://codecov.io/bash)
